### ISSUE TITLE
CustomEntityBundle requires pim-community-dev 1.2.*

### ISSUE THREAD

**Issue by loic425** [akeneo/CustomEntityBundle#16]
I haven't found any information that CustomEntityBundle is no longer compatible with pim-community-dev 1.3.*

But in composer.json file, CustomEntityBundle requires pim-community-dev 1.2.*

Is CustomEntityBundle compatible with the latest release of pim-community-dev ?

**Comment by BatsaxIV** [comment]
Hi,

You can use the 1.5 branch which is compatible with pim-community-dev 1.3.*.
It was probably not the case when you wrote this ; do a "composer require akeneo/custom-entity-bundle", it will find the appropriate version.

Jérémy.
