### ISSUE TITLE
Compatibility with PIM 1.3

### ISSUE THREAD

**Issue by BatsaxIV** [akeneo/CustomEntityBundle#8]
Hi,

Is there plan do make this bundle compatible with akeneo/pim-community-dev 1.3 ?
I suppose yes, so the next question is when ? :smiley: 

Thanks,
Jérémy.

**Comment by antoineguigan** [comment]
Hi Batsxav,

Sorry for the delay in the answer. You can use the branch 1.5 of the bundle with  CE 1.3
